##
# Copyright IBM Corporation 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

FROM ubuntu:15.10

# Latest Swift Version
ENV SWIFT_VERSION swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a
ENV SWIFT_PLATFORM ubuntu15.10

# Linux OS dependencies
RUN apt-get update && apt-get install -y \
  clang \
  curl \
  git \
  libblocksruntime-dev \
  libicu-dev \
  libpython2.7 \
  libkqueue-dev \
  libxml2 \
  wget \
  && rm -rf /var/lib/apt/lists/*


# Download and install Swift
# mv /usr/lib/lldb below from:
# https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20160425/001838.html
RUN SWIFT_ARCHIVE_NAME=$SWIFT_VERSION-$SWIFT_PLATFORM \
  && SWIFT_URL=https://swift.org/builds/development/$(echo "$SWIFT_PLATFORM" | tr -d .)/$SWIFT_VERSION/$SWIFT_ARCHIVE_NAME.tar.gz \
  && wget -nv $SWIFT_URL \
  && tar -xvzf $SWIFT_ARCHIVE_NAME.tar.gz -C / --strip 1 \
  && mv /usr/lib/lldb /usr/lib/lldb-disabled \
  && rm -rf $SWIFT_ARCHIVE_NAME* /tmp/* /var/tmp/*
